name: Update AoC Badges
on:
  schedule:
    - cron: '6 5 1-25 12 *'
  workflow_dispatch:
  push:

permissions:
  contents: write  # Accordez les permissions d'écriture

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Utilisez la dernière version de l'action

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 3230470
          session: ${{ secrets.AOC_SESSION }}                                                                           # The file that contains the badges
          dayRegex: '(?<=https:\/\/img\.shields\.io\/badge\/day%20📅-)[0-9]+(?=-blue)'                   # Regular expression that finds the content of the day badge in your file.
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%20⭐-)[0-9]+(?=-yellow)'             # Regular expression that finds the content of the stars badge in your file.
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/days%20completed-)[0-9]+(?=-red)'  # Regular expression that finds the content of the days completed badge iun your file.

      - name: Configure Git pour le push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}

      - name: Commit et push des modifications
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: README.md
