name: Update AoC Badges
on:
  schedule:
    - cron: '6 5 1-25 12 *'
  workflow_dispatch:

permissions:
  contents: write   # Ajoutez cette ligne pour accorder les permissions d'écriture

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}   # Utilisez le GITHUB_TOKEN ici
      
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 3230470
          session: ${{ secrets.AOC_SESSION }}
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: README.md